spring.application.name=RentVideos

#Spring security credentials
spring.security.user.name=dpdcentral
spring.security.user.password=Dpdcentral@1234

#Actuator mapping endpoints , It will include health,info,mappings
management.endpoints.web.exposure.include=* 

#database connection properties
spring.sql.init.platform=mysql
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/video_rentaldb?useSSL=true
spring.datasource.username=dpduser
spring.datasource.password=Dpd@1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.tomcat.max-active=200
spring.datasource.initial-size=15
spring.datasource.max-idle=5
spring.datasource.min-idle=1